name: build image to dockerhub

on:
  push:
    branches:
      - '*'
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - name: extract branch name
        run: echo "::set-env name=BRANCH_NAME::$(echo ${GITHUB_REF##*/})"

      - uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: cuotos/devto-exporter
          tag_with_ref: true
          build_args: version=${{ env.BRANCH_NAME }}