name: build image to dockerhub

on:
  push:
    branches:
      - '*'
    tags:
      - 'v*'

env:
  IMAGE_TAG: devto-exporter

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: cuotos/devto-exporter
          tag_with_ref: true
