name: build image to dockerhub

on:
  push:
    branches:
      - pipeline
    tags:
      - 'v*'

env:
  IMAGE_TAG: devto-exporter

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: cuotos/devto-exporter
          tag_with_ref: true

#      - name: login to dockerhub
#        if: success()
#        uses: actions-hub/docker/login@master
#        env:
#          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
#          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
#
#      - name: build image
#        if: success()
#        run: docker build -t cuotos/devto-exporter:${IMAGE_TAG} .
